### ISSUE TITLE
新的问题！centos 运行无法显示账号及密码

### ISSUE THREAD

**Issue by FeiNiao** [HackAllSec/XuanQiong#4]
您好，我在您更新完成后在本地windows环境下使用go环境运行源码一切正常，当我想部署在我的centos服务器上的时候服务也都启动了数据库中也含有账号及密码，可再终端却没有显示随机生成的账号及密码，这让我无法登录系统

![image](https://github.com/user-attachments/assets/d0e6562b-ec5a-4043-bcfd-4f69ba8d8dd3)

![image](https://github.com/user-attachments/assets/5c6c1e7d-1ce8-42f6-893e-5b8a7a0d7630)

数据库截图
![image](https://github.com/user-attachments/assets/499be337-ec9b-451e-b02a-556de089ec8a)

**Comment by NHPT** [comment]
xq_users表中有管理员角色账户的话是不会重新生成密码的

**Comment by FeiNiao** [comment]
已经解决了，是我数据库用户的权限问题，切换root或者赋予权限就可以了，谢谢您的解答
